# .Synopsis
#     Downloading and updating Microsoft Service Tags IP ranges
#
# .NOTES
#     Author     : Roman Rabodzei
#     Version    : 1.0.240708
#
#             _
#         .__(.)<  (MEOW)
#          \___)
#  ~~~~~~~~~~~~~~~~~~~~~~~~

name: Service Tags Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  serviceTagsUpdate:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update Service Tags
      run: |
        $Date = Get-Date -Format FileDate
        Write-Host "Downloading Service Tags..."
        $publicRawHtml = Invoke-RestMethod -Uri 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519' -UseBasicParsing
        Invoke-WebRequest ([Regex]::Match($publicRawHtml, 'https://download.microsoft.com[^"]*').Value) -OutFile .\ServiceTags_Public.json

        $govRawHtml = Invoke-RestMethod -Uri 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=57063' -UseBasicParsing
        Invoke-WebRequest ([Regex]::Match($govRawHtml, 'https://download.microsoft.com[^"]*').Value) -OutFile .\ServiceTags_Gov.json
        Write-Host "Service Tags downloaded."

    - name: Checking for changes
      run: |
        $changes = git diff --quiet || echo "changes=true" >> $GITHUB_ENV
        if (-not $changes) {
          echo "changes=false" >> $GITHUB_ENV
        }

    - name: Use changes variable
      run: |
        if ("${{ env.changes }}" -eq "true") {
          Write-Host "There are changes."
        } else {
          Write-Host "There are no changes."
        }

    - name: Commit and push changes
      if: env.changes == 'true'
      run: |
        git config --global user.name  "Roman Rabodzei"
        git config --global user.email "Roman.Rabodzei@icloud.com"
        git add .
        git commit -m "Service Tags Update $Date"
        git -c http.extraheader="AUTHORIZATION: bearer ${GITHUB_TOKEN}" push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
