name: Service Tags Update

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set git config
      run: |
        git config --global user.name  "Roman Rabodzei"
        git config --global user.email "Roman.Rabodzei@icloud.com"

    - name: Update Service Tags
      run: |
        $Date = Get-Date -Format FileDate

        $publicRawHtml = Invoke-RestMethod -Uri 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519' -UseBasicParsing
        Invoke-WebRequest ([Regex]::Match($publicRawHtml, 'https://download.microsoft.com[^"]*').Value) -OutFile .\ServiceTags_Public.json

        $govRawHtml = Invoke-RestMethod -Uri 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=57063' -UseBasicParsing
        Invoke-WebRequest ([Regex]::Match($govRawHtml, 'https://download.microsoft.com[^"]*').Value) -OutFile .\ServiceTags_Gov.json

    - name: Checking for changes
      run: |
        git diff HEAD

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Service Tags Update $Date"
        git -c http.extraheader="AUTHORIZATION: bearer ${GITHUB_TOKEN}" push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}