# .Synopsis
#     Downloading and updating Microsoft Service Tags IP ranges
#
# .NOTES
#     Author     : CoE Azure
#     Company    : Itineris NV
#     Version    : 1.0.250513
#
#             _
#         .__(.)<  (MEOW)
#          \___)
#  ~~~~~~~~~~~~~~~~~~~~~~~~

name: Sync From Upstream

on:
  schedule:
    - cron: "0 1 * * *" # daily at 1 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream and fetch
        run: |
          if ! git remote | grep -q upstream; then
            git remote add upstream https://github.com/romanrabodzei/MSFTServiceTags.git
          fi
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main || echo "Merge conflicts detected. Please resolve manually."

      - name: Push changes to fork
        if: success() # Only push if the merge was successful
        run: git push origin main
